using Microsoft.Extensions.Options;
using Options.Shared;

namespace Tier2b.OptionsGeneratorBlazor;

/// <summary>
/// The [OptionsValidator] source generator fills in the Validate() and
/// ValidateAsync() method bodies at compile time.
/// This class implements both IValidateOptions&lt;CloudInfoOptions&gt; (sync)
/// and IAsyncValidateOptions&lt;CloudInfoOptions&gt; (async).
/// </summary>
[OptionsValidator]
public partial class CloudInfoOptionsValidator
    : IValidateOptions<CloudInfoOptions>, IAsyncValidateOptions<CloudInfoOptions>
{
    // Generated by source generator:
    //   public ValidateOptionsResult Validate(string? name, CloudInfoOptions options) { ... }
    //   public ValueTask<ValidateOptionsResult> ValidateAsync(
    //       string? name, CloudInfoOptions options, CancellationToken ct = default) { ... }
}
