using Microsoft.Extensions.Options;
using Options.Shared;
using Tier2b.OptionsGeneratorBlazor;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddRazorComponents()
    .AddInteractiveServerComponents();

// ════════════════════════════════════════════════════════════════════
// TIER 2b: Source-generator-based validation
// Instead of ValidateDataAnnotationsAsync() (reflection-based),
// the generated CloudInfoOptionsValidator implements both
// IValidateOptions<T> and IAsyncValidateOptions<T>.
//
// NOTE: We only register the async interface here. The sync
// Validate() method generated by the source generator includes ALL
// validation attributes (including async-only ones), which would
// throw NotSupportedException in the sync path. By only registering
// IAsyncValidateOptions<T>, validation runs through ValidateAsync()
// which correctly handles both sync and async attributes.
// ════════════════════════════════════════════════════════════════════
builder.Services.AddOptions<CloudInfoOptions>()
    .BindConfiguration("CloudInfo");

// Register only the async validator — the sync Validate() can't handle
// AsyncValidationAttribute subclasses (they throw NotSupportedException).
builder.Services.AddSingleton<IAsyncValidateOptions<CloudInfoOptions>>(
    new CloudInfoOptionsValidator());

// Use ValidateOnStartAsync() — runs IAsyncValidateOptions<T> at startup.
builder.Services.AddOptions<CloudInfoOptions>()
    .ValidateOnStartAsync();

var app = builder.Build();

// Manually invoke async startup validation until the hosting layer
// natively integrates IAsyncStartupValidator (requires full Tier 2 merge).
var asyncValidator = app.Services.GetService<Microsoft.Extensions.Options.IAsyncStartupValidator>();
if (asyncValidator is not null)
{
    await asyncValidator.ValidateAsync();
}

app.UseStaticFiles();
app.UseAntiforgery();

app.MapRazorComponents<Tier2b.OptionsGeneratorBlazor.Components.App>()
    .AddInteractiveServerRenderMode();

app.Run();
